{% set name = "implicit" %}
{% set version = "0.3.7" %}
{% set sha256 = "4aad6c971edd47fd2f8e97b611b826f5429ee73b8bcb5a285014362da7337395" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .
  skip: True  # [win and py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython >=0.24
    - numpy
    # implicit cimports BLAS from scipy
    - scipy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('scipy') }}
    - tqdm

test:
  imports:
    - implicit
    - implicit._als

about:
  home: http://github.com/benfred/implicit/
  license: MIT
  license_family: MIT
  license_file: 'LICENSE'
  summary: 'Fast Python Collaborative Filtering for Implicit Datasets.'
  description: |
      This project provides fast Python implementations of the algorithms
      described in the paper Collaborative Filtering for Implicit Feedback
      Datasets and in Applications of the Conjugate Gradient Method
      for Implicit Feedback Collaborative Filtering
  doc_url: http://implicit.readthedocs.io/
  dev_url: http://github.com/benfred/implicit/

extra:
  recipe-maintainers:
    - rth
    - benfred
