{% set implicit_proc_type = "cpu" %}
{% set name = "implicit" %}
{% set version = "0.7.1" %}
{% set sha256 = "889c6a8f1e4c64eb5705890aa830625a7543d88757eb23ee5f6f4ba0caa8fcf3" %}
{% set number = "6" %}

{% set implicit_proc_type = "cpu" if (cuda_compiler|default("None")) == "None" else "gpu" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - patches/0001-thrust.patch

build:
  number: {{ number }}
  skip: true  # [win and cuda_compiler not in (undefined, "None")]

outputs:
  - name: implicit-proc
    version: {{ version }}
    build:
      number: {{ number }}
      string: {{ implicit_proc_type }}
    test:
      commands:
        - exit 0
    about:
      home: https://github.com/conda-forge/implicit-feedstock
      license: BSD-3-Clause
      license_family: BSD
      summary: A meta-package to select CPU or GPU implicit build.

  - name: implicit
    build:
      number: {{ number }}
      script:
        - export CMAKE_GENERATOR="Ninja"
        - python -m pip install . --no-deps -vv --no-build-isolation

    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - ninja                                  # [build_platform != target_platform]
        - cmake                                  # [build_platform != target_platform]
        - scipy >=0.16                           # [build_platform != target_platform]
        - scikit-build>=0.13.1                   # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}  # [cuda_compiler not in (undefined, "None")]
      host:
        - python
        - pip
        - wheel
        - setuptools
        - ninja
        - cmake
        - cython >=0.24
        - scikit-build>=0.13.1
        # implicit cimports BLAS from scipy
        - scipy >=0.16
        - libcublas-dev      # [(cuda_compiler_version or "").startswith("12")]
        - libcurand-dev      # [(cuda_compiler_version or "").startswith("12")]
      run:
        - python
        - {{ pin_compatible('numpy') }}
        - {{ pin_compatible('scipy') }}
        - tqdm >=4.27
      run_constrained:
        - implicit-proc * {{ implicit_proc_type }}

    test:
      imports:
        - implicit
        - implicit.cpu._als

    about:
      home: http://github.com/benfred/implicit/
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Fast Python Collaborative Filtering for Implicit Datasets.
      description: |
        This project provides fast Python implementations of the algorithms
        described in the paper Collaborative Filtering for Implicit Feedback
        Datasets and in Applications of the Conjugate Gradient Method
        for Implicit Feedback Collaborative Filtering
      doc_url: http://implicit.readthedocs.io/
      dev_url: http://github.com/benfred/implicit/

about:
  home: http://github.com/benfred/implicit/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast Python Collaborative Filtering for Implicit Datasets.
  description: |
    This project provides fast Python implementations of the algorithms
    described in the paper Collaborative Filtering for Implicit Feedback
    Datasets and in Applications of the Conjugate Gradient Method
    for Implicit Feedback Collaborative Filtering
  doc_url: http://implicit.readthedocs.io/
  dev_url: http://github.com/benfred/implicit/

extra:
  recipe-maintainers:
    - rth
    - benfred
