{% set implicit_proc_type = "cpu" %}
{% set name = "implicit" %}
{% set version = "0.7.2" %}
{% set sha256 = "bacf79120c87ad0744a4365a089409fddd33231880aef4a495bab2d4f888291d" %}
{% set number = 7 %}

{% set implicit_proc_type = "cpu" if (cuda_compiler|default("None")) == "None" else "gpu" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ number }}
  skip: true  # [win and cuda_compiler_version != "None"]

outputs:
  - name: implicit-proc
    version: {{ version }}
    build:
      number: {{ number }}
      string: {{ implicit_proc_type }}
    test:
      commands:
        - exit 0
    about:
      home: https://github.com/conda-forge/implicit-feedstock
      license: BSD-3-Clause
      license_family: BSD
      summary: A meta-package to select CPU or GPU implicit build.

  - name: implicit
    build:
      number: {{ number }}
      script_env:
        - CMAKE_GENERATOR=Ninja
      script: python -m pip install . -vv --no-deps --no-index --no-build-isolation --ignore-installed --cache-dir pip_cache

    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - {{ compiler('cuda') }}                 # [cuda_compiler_version != "None"]
        - cmake
        - ninja
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
        - cython                                 # [build_platform != target_platform]
        - scipy >=0.16                           # [build_platform != target_platform]
        - scikit-build >=0.13.1                  # [build_platform != target_platform]
      host:
        - python
        - pip
        - wheel
        - setuptools >=42
        - cython >=0.24
        - scikit-build >=0.13.1
        # implicit cimports BLAS from scipy
        - scipy >=0.16
        - libcublas-dev      # [(cuda_compiler_version or "").startswith("12")]
        - libcurand-dev      # [(cuda_compiler_version or "").startswith("12")]
        - fmt                # [cuda_compiler_version != "None"]
        - spdlog             # [cuda_compiler_version != "None"]
      run:
        - python
        - numpy >=1.17.0
        - {{ pin_compatible('scipy') }}
        - tqdm >=4.27
        - threadpoolctl
      run_constrained:
        - implicit-proc * {{ implicit_proc_type }}

    test:
      imports:
        - implicit
        - implicit.cpu._als

    about:
      home: http://github.com/benfred/implicit/
      license: MIT
      license_family: MIT
      license_file: LICENSE
      summary: Fast Python Collaborative Filtering for Implicit Datasets.
      description: |
        This project provides fast Python implementations of the algorithms
        described in the paper Collaborative Filtering for Implicit Feedback
        Datasets and in Applications of the Conjugate Gradient Method
        for Implicit Feedback Collaborative Filtering
      doc_url: http://implicit.readthedocs.io/
      dev_url: http://github.com/benfred/implicit/

about:
  home: http://github.com/benfred/implicit/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Fast Python Collaborative Filtering for Implicit Datasets.
  description: |
    This project provides fast Python implementations of the algorithms
    described in the paper Collaborative Filtering for Implicit Feedback
    Datasets and in Applications of the Conjugate Gradient Method
    for Implicit Feedback Collaborative Filtering
  doc_url: http://implicit.readthedocs.io/
  dev_url: http://github.com/benfred/implicit/

extra:
  recipe-maintainers:
    - rth
    - benfred
