travis:
  secure:
    BINSTAR_TOKEN: n7jhEk3KNLhT1OWnmmF1aGvD4PAhYXE3BzCTQHcE8LL7mbLBo++XmyJuTvGsI1X/4y1J8glqLt+VI9qmk8z2njSTsyiDPA6jsRjUKn/JkG5XJVIvvwaV8v0lJU7mKqdwrcLvELG1t1VZLHpHQOcEPAJIbTjQoYWhAdwhliIrhiSb0yhH9MTePBIC6EEbpOXRBshbyQ1fMElKJ9v8oTLiuh7kzbMroxPgBMY/7xIfT2pljYvUNgUdI/FSSBfhjZesNxa/HmDOpCin9ME9Jv1o3KexC2JtpbnfI1kz5F9cquCgVCO5txVfTHMe9i/8E41TN+0n0+Dwu4tAnyYpqBo+2aOCjGUQFmxSzjYa8TzJdHv9YCB8XNxEsDJqHsO1F/BrsZzn6ius50agDD9O42QmTKLKUyJXXD8JZzgSmIMWyGJ6JTCNxjWjsdc/vbsA46UUkikKyKFL6TydiRUBZc0X91B5LZpaJ1sN+rfbJCo/Z52iqilPHbos3Kd+uYKhr2I2KmbVwEjjpbTtyv01uP6x18toXSfrCHSkDzghrkTdP5cuMZUs0LOF/+tDRw8SpalL8MxIvQ4aCi+1nxIMgSpx6kPaiG0zoiY7chNVY60u0kHRIzk/sjQuSs8e7+lB+/a8X6wxs019sVhxVNzaxsuZY93L5ZxL2QDaGe7NBICAIAE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
